Bugfix

diff --git a/bin/backslide b/bin/backslide
--- a/bin/backslide
+++ b/bin/backslide
@@ -160,8 +160,14 @@ function set_dbus_session {
 
     # Argument #1 is name of session to look for
     PID=$(pgrep "$1" -u $UID | tail -n1)
-    DBUS_SESSION_BUS_ADDRESS=$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/"$PID"/environ | tr -d '\0' | cut -d= -f2-)
-    export DBUS_SESSION_BUS_ADDRESS
+    if [ -n "${PID}" ]
+    then
+        DBUS_SESSION_BUS_ADDRESS=$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/"$PID"/environ | tr -d '\0' | cut -d= -f2-)
+        export DBUS_SESSION_BUS_ADDRESS
+    else
+        echo "Failed to resolve $1 of user $UID, probably not logged in"
+        exit 4
+    fi
 
 }
 
@@ -185,7 +191,7 @@ then
         echo "DESKTOP_SERSSION = '${DESKTOP_SESSION}'"
         echo "MENU_PREFIX = '${XDG_MENU_PREFIX}'"
 
-        exit 4
+        exit 5
 
     fi
 fi
@@ -250,6 +256,6 @@ else
 
     # Issue warning
     echo "Unknown desktop environment ${DESKTOP}, failed to change wallpaper"
-    exit 5
+    exit 6
 
 fi
